[package]
name = "bevy_app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"

[features]
default = []
dynamic_linking = ["bevy/dynamic_linking"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom_02 = { package = "getrandom", version = "0.2", features = ["js"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
console_error_panic_hook = "0.1"
